title: Asher Raz
description: My webpage
baseurl: ""
url: https://asherraz.github.io

#theme: cvless

# site settings
taglong: Hmm... Yep
tagshort:

# author settings
author:
  name: Asher Raz
  email: gmon01
photo: assets/files/ash.JPG

# social media links
social:
  github: asherraz
  # wordpress: alsoofthetreeoflife
  # google_scholar: citations?user=wswTSOoAAAAJ&hl=en
  linkedin: ashraz
  # substack: tomerlan
  x: ash_raziel
# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-analytics
analytics:
  provider: google
  google:
    tracking_id: G-DMHRV5LZQL
exclude: ['archive']
